# PowerShell script for setting up environment variables
$env:GOOGLE_APPLICATION_CREDENTIALS = 'C:\dev\CODE\Confluence_firebase\keys\firebase-adminsdk-key.json'
$env:GEMINI_API_KEY = 'AIzaSyA6YvXHeaXByWy64MMOMLSMzO1ctQCXcTs'
$env:VERTEX_AI_PROJECT_ID = 'confluence-copilot-ppjye'
$env:VERTEX_AI_LOCATION = 'asia-northeast1'
$env:VERTEX_AI_INDEX_ID = '8470329717130526720'
$env:VERTEX_AI_ENDPOINT_ID = '1242272217526435840'
$env:VERTEX_AI_DEPLOYED_INDEX_ID = 'confluence_embeddings_v2_deployed'
$env:VERTEX_AI_NUMERIC_PROJECT_ID = '122015916118'
$env:VERTEX_AI_STORAGE_BUCKET = 'confluence-copilot-ppjye-vector-search'
$env:VERTEX_AI_PUBLIC_ENDPOINT_DOMAIN = '1010669901.asia-northeast1-122015916118.vdb.vertexai.goog'

Write-Host "環境変数を設定しました:"
Write-Host "GOOGLE_APPLICATION_CREDENTIALS: $env:GOOGLE_APPLICATION_CREDENTIALS"
Write-Host "GEMINI_API_KEY: $env:GEMINI_API_KEY"
Write-Host "VERTEX_AI_PROJECT_ID: $env:VERTEX_AI_PROJECT_ID"
Write-Host "VERTEX_AI_LOCATION: $env:VERTEX_AI_LOCATION"
Write-Host "VERTEX_AI_INDEX_ID: $env:VERTEX_AI_INDEX_ID"
Write-Host "VERTEX_AI_ENDPOINT_ID: $env:VERTEX_AI_ENDPOINT_ID"
Write-Host "VERTEX_AI_DEPLOYED_INDEX_ID: $env:VERTEX_AI_DEPLOYED_INDEX_ID"
Write-Host "VERTEX_AI_NUMERIC_PROJECT_ID: $env:VERTEX_AI_NUMERIC_PROJECT_ID"
Write-Host "VERTEX_AI_STORAGE_BUCKET: $env:VERTEX_AI_STORAGE_BUCKET"
Write-Host "VERTEX_AI_PUBLIC_ENDPOINT_DOMAIN: $env:VERTEX_AI_PUBLIC_ENDPOINT_DOMAIN"
